
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#general]
== General features and fixes

Information in this section applies to all architectures supported by {product} {this-version}.


[#install-media]
=== Installation media

There are two types of installation media of {product}.
The installer ISO allows to install via YaST or AutoYaST, with the possibility to fully customize the installation.
The pre-built images contain a system image already pre-configured.
Neither of the media is intended to be used for upgrades from the previous version of {product}.

There are slight differences between these two:

* the software selection for the default installation from the ISO contains fewer packages than the pre-built image
* `firewalld` is only installed from the ISO if the firewall is enabled during installation

The images have two things in common:

* SELinux is not enabled by default
* `firewalld` is not enabled by default

[#general-cockpit]
=== Cockpit web-based node management system

For web-based management of a single node, Cockpit is included.

Cockpit is not enabled by default and its firewall port is not open if the firewall is enabled.
For more information, see <<#issue-firewalld-cockpit>>.


[#general-suma]
=== Managing {product} with {suma}

{suma} can be used to manage {product} hosts.
There are certain limitations:
* Installing additional software or patching the system does not work with the Web UI because `transactional-update` needs to be used instead of `zypper`.
As a workaround, you can execute remote commands and call `transactional-update` tool on the {product} host.
* {product} host cannot be monitored with {suma}
* {suma} does not provide integrated container management yet.
As a workaround, you can use Salt via `cmd.run podman`.
We intend to resolve these issues in the future maintenance updates of {suma}.


[#general-selinux]
=== Enabling SELinux

{product} includes SELinux with base system policies.
Before enabling SELinux, make sure to install the necessary policies for your workload.

If you are running {product} as KVM virtualization host, the use of SELinux is strongly discouraged.


[#general-toolbox]
=== `toolbox` container

{product} provides the `toolbox` container.
However, it is not part of the media and needs to be downloaded from https://registry.suse.com.
To download from the registry, the system needs network access.

The `toolbox` container does not include or inherit a software repository setup from the underlying system.
If the underlying system is registered properly, `zypper` will enable a basic set of repositories (`Basesystem` and `Server Applications` modules of {sles} 15{nbsp}SP2) when you execute it.
Then you can install additional software into the container.


[#general-livepatch]
=== Kernel Live Patching

{product} now supports Kernel Live Patching.
If your subscription includes it, you can either install it directly during the installation, or register the Live Patching module later using the `transactional update` command.

[#general-sdo]
=== {sdo} (SDO)

{product} includes needed packages for {sdo}.
{sdo} helps onboard any device to any device management system.
The packages are only provided as a technology preview and do not offer full support.
Using {sdo} needs proper integration into your target environment and only works on supported hardware.


[#general-sysv-support]
=== System V init scripts

{product} does not support init script of system services, which are usually located in `/etc/init.d` directory.
Even if this directory still exists, it is empty on purpose.
systemd unit files should be used instead of initscripts.
To start system services or to configure their status on boot, use the `systemctl` command instead.
