
include::entities-generic.adoc[]
include::entities-product.adoc[]

[#general]
== General Features & Fixes

Information in this section applies to all architectures supported by {product} {this-version}.

=== Installation Media

There are two types of installation media of {product}.
The installer ISO allows to install via YaST or AutoYaST, with the possibility to fully customize the installation.
The pre-built images contain a system image already pre-configured.

There are slight differences between these two:

* the software selection for default installation from ISO contains fewer packages than the pre-built image
* `firewalld` is installed from the ISO only if it gets enabled during installation

The images have two things in common:
* SELinux is not enabled by default
* firewall is not enabled by default

=== Podman and `firewalld`

When reloading `firewalld` via `firewall-cmd --reload`, all Podman related rules go missing.
This is a known issue:

https://github.com/containers/podman/issues/5431

Because of that, firewalld is not enabled by default installation.

=== Cockpit

For web-based management of a single node, Cockpit web management is included.
It is not enabled by default and the respective firewall port is not open if firewall is enabled.

=== Toolbox Container

{product} provides the toolbox container.
However, it is not part of the media and needs to be downloaded from registry.suse.com.
For that the system needs to have access to the registry.

In order to install additional software into the container, you must configure the repositories.
it does not define any nor does it inherit repositories from the underlying system.
