
include::entities-generic.adoc[]
include::entities-product.adoc[]

[#general]
== General features and fixes

Information in this section applies to all architectures supported by {product} {this-version}.


[#install-media]
=== Installation media

There are two types of installation media of {product}.
The installer ISO allows to install via YaST or AutoYaST, with the possibility to fully customize the installation.
The pre-built images contain a system image already pre-configured.

There are slight differences between these two:

* the software selection for the default installation from the ISO contains fewer packages than the pre-built image
* `firewalld` is only installed from the ISO if the firewall is enabled during installation

The images have two things in common:

* SELinux is not enabled by default
* `firewalld` is not enabled by default


[#general-cockpit]
=== Cockpit web-based node management system

For web-based management of a single node, Cockpit is included.

Cockpit is not enabled by default and its firewall port is not open if the firewall is enabled.
For more information, see <<#issue-firewalld-cockpit>>.


[#general-toolbox]
=== `toolbox` container

{product} provides the `toolbox` container.
However, it is not part of the media and needs to be downloaded from https://registry.suse.com.
To download from the registry, the system needs network access.

The `toolbox` container does not include or inherit a software repository setup from the underlying system.
To install additional software into the container, you must configure repositories manually.


[#general-sysv-support]
=== System V init scripts

{product} does not support init script of system services, which are usually located in `/etc/init.d` directory.
Even if this directory still exists, it is empty on purpose.
systemd unit files should be used instead of initscripts.
To start system services or to configure their status on boot, use the `systemctl` command instead.
