include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#general]
== General features and fixes

Information in this section applies to all architectures supported by {product} {this-version}.


[#install-media]
=== Installation media

There are two types of installation media of {product}.
The installer ISO allows to install via YaST or AutoYaST, with the possibility to fully customize the installation.
The pre-built images contain a system image already pre-configured.
Neither of the media is intended to be used for upgrades from the previous version of {product}.

There are slight differences between these two:

* the software selection for the default installation from the ISO contains fewer packages than the pre-built image
* `firewalld` is only installed from the ISO if the firewall is enabled during installation

The images have two things in common:

* SELinux is not enabled by default
* `firewalld` is not enabled by default

To upgrade from the previous version, use the `transactional-update` command. Neither of the media is needed for that.


[#general-cockpit]
=== Cockpit web-based node management system

For web-based management of a single node, Cockpit is included. 
For details, refer to {doc-url}/html/SLE-Micro-all/article-administration-slemicro.html#sec-admin-cockpit.

Compared to the previous release, Cockpit has been updated to the latest version.
Due to limited functionality, the Dashboard screen has been removed with this release.

[#general-suma]
=== Managing {product} with {suma}

{suma} can be used to manage {product} hosts.
There are certain limitations:

* {product} host cannot be monitored with {suma}
* {suma} does not provide integrated container management yet. As a workaround, you can use Salt via `cmd.run podman`.
* {suma} can manage the {product} hosts ony with the Salt stack; the traditional stack is not supported
* Ansible control node cannot be instaled on {product}

We intend to resolve these issues in the future maintenance updates of {product} on {suma}.


[#general-selinux]
=== Enabling SELinux

{product} includes SELinux with base system policies.
Before enabling SELinux, make sure to install the necessary policies for your workload.

If you are running {product} as KVM virtualization host, the use of SELinux is strongly discouraged and not supported.

Note that the pre-built images enable SELinux by default in the permissive mode.


[#general-toolbox]
=== `toolbox` container

{product} provides the `toolbox` container.
However, it is not part of the media and needs to be downloaded from https://registry.suse.com.
To download from the registry, the system needs network access. 
For details refer to {doc-url}/html/SLE-Micro-all/article-administration-slemicro.html#sec-admin-toolbox.

The `toolbox` container does not include or inherit a software repository setup from the underlying system.
If the underlying system is registered properly, `zypper` will enable a basic set of repositories (`Basesystem` and `Server Applications` modules of {sles} 15{nbsp}SP3) when you execute `zypper` inside the toolbox container.
Then you can install additional software into the container.


[#general-livepatch]
=== Kernel Live Patching

{product} supports Kernel Live Patching, for details refer to {doc-url}/html/SLE-Micro-all/cha-images-procedure.html#sec-slemicro-live-patching.

Note that kernel live patching is only available for the x86-64 and s390x architectures. It is also not available for the real-time kernel.

[#general-sdo]
=== {sdo} (SDO)

{product} includes needed packages for {sdo}.
{sdo} helps onboard any device to any device management system.
With this release, the SDO client has been replaced with FDO client, which is a portable implementation of the FIDO Device Onboard Spec.
The packages are only provided as a technology preview and do not offer full support.
Using {sdo} needs proper integration into your target environment and only works on supported hardware.


[#general-sysv-support]
=== System V init scripts

{product} does not support init script of system services, which are usually located in `/etc/init.d` directory.
Even if this directory still exists, it is empty on purpose.
systemd unit files should be used instead of initscripts.
To start system services or to configure their status on boot, use the `systemctl` command instead.


[#pattern-rename]
=== Rename of the `microos-sssd_ldap` pattern

The `microos_sssd_ldap` pattern has been renamed to `microos-sssd_ldap` (the first dash has been replaced with an underscore).
This new name is consistent with other pattern names.
Note that your AutoYaST profile may need updating.
