
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#installation]
== Installing {product}

{product} {this-version} can be installed in the following ways:

* <<#install-yast>>
* <<#install-autoyast>>
* <<#install-yomi>>
* <<#deploy-image>>


[#install-yast]
=== Manually installing with YaST

The installation workflow for manual installation is described in {doc-url}/html/SLE-Micro-all/part-manual-installation.html.


[#install-autoyast]
=== Unattended installation with {autoyast}

Installing {product} with {autoyast} is described in {doc-url}/html/SLE-Micro-all/book-autoyast.html.

 
[#install-yomi]
=== Unattended installation with Yomi (technology preview)

To learn how to install a system with Yomi, see the link:https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/salt/yomi.html[{suma} documentation, section Install using Yomi].
Installation with Yomi is a technology preview.


[#deploy-image]
=== Deploying pre-built images

{product} is provided as raw images which can be deployed directly to a storage device, for example, a memory card, a USB stick, or a hard drive.
{product} is also provided as images for specific hardware device with a customized software selection.

For a procedure of deploying an image refer to {doc-url}/html/SLE-Micro-all/part-raw-image.html 

[#upgrade]
=== Upgrade from previous version

Upgrade from {producta} {previous-version} is only possible via the `transactional-update` tool.
For the upgrade procedure, refer to {doc-url}/html/SLE-Micro-all/book-upgrade.html.

