
include::entities-generic.adoc[]
include::entities-product.adoc[]

[#installation]
== Installing {product}

{product} {this-version} can be installed in the following ways:

* manual installation with YaST
* unattended installation with AutoYaST
* unattended installation with Yomi (technology preview)
* deployment of pre-built images

Below find notes to individual approaches.


=== Manual installation with YaST

The installation workflow for manual installation is similar to {sles}.
However, it is stripped down and configuration options are more limited.
For more information, see the {sles} documentation.


=== Unattended installation with AutoYaST

The installation with AutoYaST works in a similar way as for {sles}.
The two main differences are limited set of options that can be configured via the AutoYaST profile and complete absence of the second stage of the AutoYaST workflow.
For more information, see the {product} and {sles} documentation.

The following example shows an AutoYaST profile:

[source,xml]
....
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <suse_register>
    <do_registration config:type="boolean">true</do_registration>
    <reg_code>YOUR_REGISTRATION_CODE</reg_code>
    <install_updates config:type="boolean">true</install_updates>
    <reg_server>http://YOUR_SMT_SERVER</reg_server>
  </suse_register>
  <bootloader>
    <global>
      <timeout config:type="integer">-1</timeout>
      <hiddenmenu>false</hiddenmenu>
    </global>
  </bootloader>
  <general>
    <mode>
      <confirm config:type="boolean">false</confirm>
      <second_stage config:type="boolean">false</second_stage>
    </mode>
  </general>
  <software>
    <products config:type="list">
      <product>SUSE-MicroOS</product>
    </products>
    <install_recommended config:type="boolean">true</install_recommended>
    <packages config:type="list">
      <package>grub2</package>
    </packages>
    <patterns config:type="list">
      <pattern>basesystem</pattern>
      <pattern>microos-container_runtime</pattern>
      <pattern>microos-selinux</pattern>
    </patterns>
  </software>
  <users config:type="list">
    <user>
      <encrypted config:type="boolean">false</encrypted>
      <user_password>ROOT_PASSWORD</user_password>
      <username>root</username>
    </user>
  </users>
</profile>
....

{autoyast} only supports a limited set of sections compared to {sles}:

* `bootloader`
* `configuration_management`
* `fcoe-client`
* `files`
* `firewall`
* `groups`
* `general`
* `host`
* `iscsi-client`
* `kdump`
* `keyboard`
* `language`
* `login_settings`
* `networking`
* `partitioning`
* `partitioning_advanced`
* `report`
* `runlevel` / `services-manager`
* `scripts` (`pre-scripts`, `postpartitioning-scripts`, `chroot-scripts`)
* `security`
* `software`
* `ssh_import`
* `suse_register`
* `timezone`
* `users`
* `user_defaults`

[NOTE]
.Explicitly disable the second stage
====
{autoyast} can set some options in either the first or the second stage.
{product} does not include a second stage.
For some settings (such as networking), you need to explicitly disable the second stage:

[source,xml]
....
<second_stage config:type="boolean">false</second_stage>
....

The example profile above already includes this line.
====

[NOTE]
.SELinux is necessary
The system will not boot if you do not install the SELinux pattern and keep SELinux enabled.


=== Unattended installation with Yomi (technology preview)

To learn how to install a system with Yomi, read the documentation of SUSE Manager.
Installation with Yomi is only a technology preview.


=== Deployment of pre-built images

{product} is provided as raw images which can be deployed directly to a storage device, for example, a memory card, a USB stick, or a hard drive.
{product} is also provided as images for specific hardware device with a customized software selection.

To deploy an image, first identify and download the image you need.
Then decompress it and write it to a storage device:

[source,bash]
....
xz -d <downloaded_image.raw.xz>
dd if=<downloaded_image.raw> of=/dev/sdX
....

When the image is first booted, use Ignition or Combustion for initial configuration, which includes setting the root password.
Otherwise, there is no way to access the system after deployment.

Ignition or Combustion are invoked only the first time the image boots.
To invoke them at a later reboot, append `ignition.firstboot` to the kernel command line.

Ignition configuration files should be named `ignition/config.ign`, and can be stored on a USB stick.
A minimal Ignition configuration file could look like this:

[source,json]
....
{
  "ignition":{
    "version":"3.1.0"
  },
  "passwd":{
    "users":[
      {
        "name":"root",
        "passwordHash":"hash, created with, for example, `openssl passwd -6`"
      }
    ]
  }
}
....

More information about Ignition and Combustion, including further examples, can be found at the these links:

* https://en.opensuse.org/Portal:MicroOS/Ignition
* https://en.opensuse.org/Portal:MicroOS/Combustion
