
include::entities-generic.adoc[]
include::entities-product.adoc[]

[#installation]
== Installing {product}

{product} {this-version} can be installed in the following ways:

* manual installation with YaST
* unattended installation with AutoYaST
* unattended installation with Yomi (technology preview)
* deployment of pre-built images

Below find notes to individual approaches.

=== Manual Installation with YaST

The installation workflow for manual installation is similar to {SLES}.
However, it is stripped down and the amount of configuration options is limited.
For more information see the {sles} documentation.

=== Unattended Installation with AutoYaST

The installation with AutoYaST works in a similar way as for {SLES}.
The two main differenes are limited set of options that can be configured via the AutoYaST profile and complete absence of the second stage of the AutoYaST workflow. For more details see the {product} and {SLES} documentation.
Below comes an example of an AutoYaST profile:

[source,xml]
....
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <suse_register>
    <do_registration config:type="boolean">true</do_registration>
    <reg_code>YOUR_REGISTRATION_CODE</reg_code>
    <install_updates config:type="boolean">true</install_updates>
    <reg_server>http://YOUR_SMT_SERVER</reg_server>
  </suse_register>
  <bootloader>
    <global>
      <timeout config:type="integer">-1</timeout>
      <hiddenmenu>false</hiddenmenu>
    </global>
  </bootloader>
  <general>
    <mode>
      <confirm config:type="boolean">false</confirm>
      <second_stage config:type="boolean">false</second_stage>
    </mode>
  </general>
  <software>
    <products config:type="list">
      <product>SUSE-MicroOS</product>
    </products>
    <install_recommended config:type="boolean">true</install_recommended>
    <packages config:type="list">
      <package>grub2</package>
    </packages>
    <patterns config:type="list">
      <pattern>basesystem</pattern>
      <pattern>microos-container_runtime</pattern>
      <pattern>microos-selinux</pattern>
    </patterns>
  </software>
  <users config:type="list">
    <user>
      <encrypted config:type="boolean">false</encrypted>
      <user_password>ROOT_PASSWORD</user_password>
      <username>root</username>
    </user>
  </users>
</profile>
....

{autoyast} only supports limited set of sections compared to {sles}:

* `iscsi-client`
* `fcoe-client`
* `scripts` (`pre-scripts`, `postpartitioning-scripts`, `chroot-scripts`)
* `report`
* `general`
* `add-on`
* `suse_register`
* `networking`
* `keyboard`
* `language`
* `partitioning`
* `partitioning_advanced`
* `configuration_management`
* `runlevel / services-manager`
* `ssh_import`
* `security`

[NOTE]
{autoyast} is capable of setting some of the options in either first or second stage.
Since {product} does not include 2nd stage, for some of the setting it is necessary to specify explicitly that 2nd stage would not run via
....
<second_stage config:type="boolean">false</second_stage>
....
as in the example above.

[NOTE]
The system will not boot if you do not install the SELinux pattern and keep SELinux enabled.

=== Unattended installation with Yomi (technology preview)

To learn how to install a system with Yomi, read the documentation of SUSE Manager.
Installation with Yomi is only a technology preview.

=== Deployment of pre-built images

{product} provides raw images which can be deployed directly to the storage of the device, for example, memory card, USB stick or a hard drive.
{product} provides images for specific hardware device with specific software selection.

To deploy the image, identify and download the image you need.
After decompressing it, dump it to the respective device:

[source,bash]
....
xz -d <downloaded_image.raw.xz>
dd if=<downloaded_image.raw> of=/dev/sdX
....

When the image is booted for the first time, you should use Ignition or Combustion for initial configuration
(including setting the root password), otherwise there is no way to access the system after deployment.

Ignition or Combustion are invoked only the first time the image boots.
In order to invoke it at a later reboot, append `ignition.firstboot` to the kernel command line.

The minimal Ignition configuration file, which would be stored as `ignition/config.ign` on a USB stick, could look like this:

[source,json]
....
{
  "ignition":{
    "version":"3.1.0"
  },
  "passwd":{
    "users":[
      {
        "name":"root",
        "passwordHash":"hash, created with, for example, `openssl passwd -6`"
      }
    ]
  }
}
....

More information about Ignition and Combustion, including further examples, can be found at the these links:

* https://en.opensuse.org/Portal:MicroOS/Ignition
* https://en.opensuse.org/Portal:MicroOS/Combustion
