
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#known-issue]
== Known issues


[#issue-selinux-boot]
=== Error on console while booting with SELinux enabled

When booting the system with SELinux enabled, the console reports:

....
Failed to transition into init label 'system_u:system_r:init_t:s0'
....

This message is harmless.


[#issue-firewalld-podman]
=== Podman and `firewalld`

When reloading `firewalld` via `firewall-cmd --reload`, all Podman-related rules go missing.
For this reason, `firewalld` is not enabled by default during installation.
For more information, see https://github.com/containers/podman/issues/5431.


[#issue-duplicate-ip-address]
=== Pre-built images report two IP addresses on first boot

When booting the pre-built images the first time, two IP addresses may be reported by the `ip a` command or other tools.
This issue only happens on the first boot of the image, on the following boots only a single IP address is assigned to the network interface.


[#issue-install-vnc]
=== VNC package cannot be installed during installation

The {yast} installer offers installation via VNC.
The installer also tries to make it possible to use the final system the same way that the system was initially installed.
Therefore, the installer will attempt to install appropriate software and open appropriate firewall ports for later access to the system.
However, the VNC server package is only available during the installation, but not for the installed system.

As the VNC server package cannot be installed, the installer will issue a warning.
You can safely ignore this warning.

[#issue-update-apparmor]
=== AppArmor error messages in log after upgrade

Leap Micro supports SELinux as the security framework, however, some AppArmor packages are still included because of package dependencies.
Since they have been reduced since Leap Micro 5.1, it may happen that there are error messages showing in the system journal after upgrade.
If this happens, make sure that the `apparmor.service` service is not enabled in your system.
