
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#known-issue]
== Known issues


[#issue-selinux-boot]
=== Error on console while booting with SELinux enabled

When booting the system with SELinux enabled, the console reports:

....
Failed to transition into init label 'system_u:system_r:init_t:s0'
....

This message is harmless.


[#issue-firewalld-podman]
=== Podman and `firewalld`

When reloading `firewalld` via `firewall-cmd --reload`, all Podman-related rules go missing.
For this reason, `firewalld` is not enabled by default during installation.
For more information, see https://github.com/containers/podman/issues/5431.


[#issue-firewalld-cockpit]
=== Cockpit service not known to `firewalld`

`firewalld` does not know the Cockpit service.
As a workaround, open the port in `firewalld` by typing this command:

[source,shell]
....
firewall-cmd --zone=public --permanent --add-port=9090/tcp
....


[#issue-install-vnc]
=== VNC package cannot be installed during installation

The {yast} installer offers installation via VNC.
The installer also tries to make it possible to use the final system the same way that the system was initially installed.
Therefore, the installer will attempt to install appropriate software and open appropriate firewall ports for later access to the system.
However, the VNC server package is only available during the installation, but not for the installed system.

As the VNC server package cannot be installed, the installer will issue a warning.
You can safely ignore this warning.
