
include::entities-generic.adoc[]
include::entities-product.adoc[]

[#known_issues]
== Known issues

=== Error on console while booting with SELinux enabled

When booting the system with SELinux enabled, the console reports:

....
Failed to transition into init label 'system_u:system_r:init_t:s0'
....

This message is harmless.


=== Podman and `firewalld`

When reloading `firewalld` via `firewall-cmd --reload`, all Podman related rules go missing.
For this reason, `firewalld` is not enabled by default during installation.
For more information, see https://github.com/containers/podman/issues/5431.


=== Cockpit not known by `firewalld`

`firewalld` does not know the Cockpit service.
As a workaround, open the port in `firewalld` by typing this command:

[source,shell]
....
firewall-cmd --zone=public --permanent --add-port=9090/tcp
....


=== Installation via VNC

The {yast} installer offers installation via VNC.
However, the VNC server is only available during the installation, but not for the installed system.
The installer issues a warning that the respective packages cannot be installed.
This is correct, you can ignore this warning.
